<?php
defined('_JEXEC') or die('Restricted access'); 

JText::script('OEMPREGO_SCRIPT_VALIDATE_ERROR_INPUT_REQUIRED');
JText::script('OEMPREGO_SCRIPT_VALIDATE_ERROR_INPUT_EMAIL');
JText::script('OEMPREGO_SCRIPT_VALIDATE_ERROR_INPUT_EQUALSPASS');
JText::script('OEMPREGO_SCRIPT_VALIDATE_ERROR_INPUT_PASSWORD');

JText::script('OEMPREGO_SCRIPT_VALIDATE_ERROR_INPUT_CPF');
JText::script('OEMPREGO_SCRIPT_VALIDATE_ERROR_INPUT_CNPJ');







?>