<?php
defined('_JEXEC') or die('Restricted access'); 
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_REQUIRED');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_CPF');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_CPF_REPEAT');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_EQUALSPASS');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_PASSWORD2');

?>