<?php
defined('_JEXEC') or die('Restricted access');

JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_REQUIRED');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_EMAIL');

JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_CNPJ');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_CPF');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_CPF_REPEAT');
JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_CNPJ_REPEAT');


JText::script('EASISTEMAS_SCRIPT_VALIDATE_ERROR_INPUT_DATE');
JText::script('EASISTEMAS_SCRIPT_SELET_LOADING');
JText::script('EASISTEMAS_GLOBAL_CIDADE');
JText::script('EASISTEMAS_GLOBAL_BUTTON_NEW_SEARCH');
JText::script('EASISTEMAS_GLOBAL_BUTTON_SEARCH');
JText::script('EASISTEMAS_SCRIPT_HOME_JQUERY_NO_RESULT');